# Generated by Django 5.0.6 on 2024-06-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
