# Generated by Django 5.0.6 on 2024-07-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_producto_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
