# Generated by Django 5.0.6 on 2024-07-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[(0, 'Comisiones'), (1, 'Tatuajes'), (2, 'Sugerencias'), (3, 'Felicitaciones'), (4, 'Reclamos')])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
